### ISSUE TITLE
TOC is not changed by this extension

### ISSUE THREAD

**Issue by DahlitzFlorian** [kdeldycke/mdx_titlecase#3]
If this extension is used together with the built-in toc-extension, the inline headers are modified, but the links In the TOC remain in the original case.

This can be changed by changing the location from `_end` to `_begin`.

Is there any reason, why not changing the location? Is something else breaking if changed?

**Comment by kdeldycke** [comment]
Thanks @DahlitzFlorian for the bug report and the fix!

FYI, I'm planning to re-package this extension soon a release it on PyPi.
